[project]
name = "claude-memory-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anyio>=4.9.0",
    "claude-code-sdk>=0.0.11",
    "sentence-transformers>=4.1.0",
]
